apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ $.Values.global.awsAccountId }}.dkr.ecr.{{ $.Values.global.awsRegion }}.amazonaws.com/{{ $.Values.global.ecr.frontendRepo }}:{{ $.Values.global.imageTags.frontendTag }}"
          ports:
            - containerPort: {{ .Values.global.service.frontendPort }}
