apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc2-app
  namespace: tc2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tc2-app
  template:
    metadata:
      labels:
        app: tc2-app
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: tc2-app
      containers:
        - name: tc2-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
